import type { Metadata } from "next";
import { DM_Mono, Archivo } from "next/font/google";
import "./globals.css";

const dmMono = DM_Mono({
  variable: "--font-dmMono-mono",
  subsets: ["latin"],
  weight: ["300", "400", "500"],
});

const archivo = Archivo({
  variable: "--font-archivo-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${dmMono.variable} ${archivo.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
